### ISSUE TITLE
Add elements by using a path

### ISSUE THREAD

**Issue by ypflanzer** [BitPuffin/sexpresso#1] opened 2016-04-04 10:38 UTC
A nice feature would be adding expressions by calling some method like

`addExpression(const std::string& path, const std::string& value)`

so it is possible to simply do something like this:
`tree.addExpression("config/render/fxaa", "true");`

Or for more complicated stuff:
`tree.addExpression("config/render/clear-color", "(r 0) (g 0) (b 0)");`

Accessing them should be done by calling 
`tree.getChildByPath("config/render/fxaa")`
and 
`tree.getChildByPath("config/render/clear-color/r")`
for each component.

**Comment by BitPuffin** [comment] 2016-04-06 00:51
I think an `addExpression` could be very useful, though I don't think it should take the path. It should probably just parse an input string expression and add its values as children.

So the usage would look something like.

```
s.getChildByPath("config/reader/clear-color")->addExpression("(r 0) (g 0) (b 0)");
```

The problem is that you would be dereferencing a nullptr if the path does not exist. So, maybe the purpose of your path string is to also create the path? If so, my suggestion for how it should be would still involve two calls:

```
s.createPath("config/reader/clear-color").addExpression("(r 0) (g 0) (b 0)");
```

Where `createPath` creates the path (obviously), and also returns a reference to the node at the end of the path. By calling addExpression on this reference, the parser will parse the string and add the resulting children.

**Comment by ypflanzer** [comment] 2016-04-06 07:21
That's exactly what I thought of. It should of course create the path or else it would become rather useless.
Your approach looks nice, looking forward to using it.

**Comment by BitPuffin** [comment] 2016-04-06 21:46
Addressed by https://github.com/BitPuffin/sexpresso/commit/a6f0bbc52422987cc452a120a5d7c40a9fbbe20b

**Closed as completed by BitPuffin** 2016-04-06 21:46 UTC
